import Head from "next/head"

import Link from "next/link"

const HomePage = () => {
  return (
    <>
      <Head>
        <title>RTK Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Next.js RTK-Query Demo page</h1>
      <h2>take a look at some pokemon</h2>
    </>
  )
}

export default HomePage
