import Head from "next/head"
import styles from "../styles/Home.module.css"

const HomePage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RTK Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Next.js RTK-Query Demo page</h1>
    </div>
  )
}

export default HomePage
